defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: false
controller:
  manager:
    clientCache:
      persistenceModel: none # direct-encrypted
      # storageEncryption:
      #   enabled: true
      #   mount: demo-auth-mount  #k8s auth engine name
      #   keyName: vso-client-cache
      #   namespace: us-west-org
      #   transitMount: demo-transit # transit engine name
      #   kubernetes:
      #     role: auth-role-operator
      #     serviceAccount: vault-secrets-operator-controller-manager
      #     tokenAudiences: ["vault"]
